spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 300000   #  prevents "connection closed" warnings
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379

  data:
    redis:
      repositories:
        enabled: false

server:
  port: 9999